:::  {.content-visible when-meta="includeIntroductionTexts"}
```{r}
#| output: asis
include_localised("_fig-intro-gestational-age.qmd")
```
:::

```{r}
#| label: fig-ga
#| fig-cap: !expr 'paste(sR$`fig-ga`$`fig-cap`[[1]], sprintf(if("ref" %in% benchmark_data$dataset_names) sR$`fig-ga`$`fig-cap`[[2]]$bnch else sR$`fig-ga`$`fig-cap`[[2]]$`no-bnch`, sprintf("%i%s%s", 7L, sR$unit_separator, sR$day)), sprintf(if("ref" %in% benchmark_data$dataset_names) sR$`fig-ga`$`fig-cap`[[3]]$bnch else sR$`fig-ga`$`fig-cap`[[3]]$`no-bnch`, sprintf("%i%s", 25L, sR$percent_symbol), sprintf("%i%s", 50L, sR$percent_symbol), sprintf("%i%s", 75L, sR$percent_symbol)))'

check_figure_interpretation <- "ref" %in% benchmark_data$dataset_names

week_breaks <- function(x) {
  pretty(
    x / 7,
    as.integer((as.integer(x[2] / 7) + 1 - as.integer(x[1] / 7)) / 2)
    ) * 7
}
week_labels <- function(x) {
  paste(
    format(
      as.integer(x / 7),
      big.mark = sR$digit_group_separator
      ),
    sR$week_abbreviation,
    sep = sR$unit_separator)
}

legend_position <- 'none'
ga_scale_min <- benchmark_data$gestational_age_figure$scale$min |>
  min()
ga_scale_max <- benchmark_data$gestational_age_figure$scale$max |>
  max()

histogram_data <- benchmark_data$gestational_age_figure$frequency |>
  dplyr::filter(dataset == "own")

density_data <- benchmark_data$gestational_age_figure$density |>
  dplyr::filter(dataset == "own")

density_factor <- sum(histogram_data$n) *
  (nrow(density_data) / length(seq.int(from = min(density_data$gestational_age), to = max(density_data$gestational_age), by = 7L)))

A_plot <- ggplot() +
  geom_col(
    data = histogram_data,
    aes(
      x = gestational_age_cat,
      y = n,
      colour = "own"),
    fill = "white")

if ("ref" %in% benchmark_data$dataset_names) {
  legend_position <- 'bottom'

density_data_ref <- benchmark_data$gestational_age_figure$density |>
  dplyr::filter(dataset == "ref")

  density_factor_ref <-  density_factor *
    (
      density_data$gestational_age |> max() -
        density_data$gestational_age |> min()) /
    (
      density_data_ref$gestational_age |> max() -
        density_data_ref$gestational_age |> min())

  A_plot <- A_plot +
    geom_line(
      data = density_data_ref,
      aes(
        x = gestational_age,
        y = density * density_factor_ref,
        colour = "ref"))
}

A_plot <- A_plot +
  geom_line(
    data = density_data,
    aes(
      x = gestational_age,
      y = density * density_factor,
      colour = "own")) +
  scale_x_continuous(breaks = week_breaks) +
  scale_colour_manual(values = rev(pal[2:3])) +
  coord_cartesian(xlim = c(ga_scale_min, ga_scale_max)) +
  theme(
    legend.position = "none",
    plot.tag = element_text(size = 9),
    axis.title = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    panel.grid.major.y = element_blank(),
    panel.grid.minor.y = element_blank()) +
  labs(tag = "A")

B_plot <- ggplot(
  benchmark_data$gestational_age_figure$location_parameters |>
    mutate(
      dataset = dplyr::case_match(
        as.character(.data$dataset),
        "own" ~ sR$own_unit,
        "ref" ~ sR$reference_data)),
  aes(dataset, colour = dataset)) +
  geom_boxplot(
    aes(ymin = q1, lower = q1, middle = q2, upper = q3, ymax = q3),
    stat = "identity",
    outlier.shape = NA,
    ) +
  geom_point(aes(y = mean), shape = 23, size = 3, fill = "white") +
  scale_y_continuous(breaks = week_breaks, labels = week_labels) +
  scale_colour_manual(values = rev(pal[2:3])) +
  coord_flip(ylim = c(ga_scale_min, ga_scale_max)) +
  theme(
    legend.title = element_blank(),
    legend.position = legend_position,
    plot.tag = element_text(size = 9),
    axis.title = element_blank(),
    axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    panel.grid.major.y = element_blank(),
    panel.grid.minor.y = element_blank()) +
  labs(tag = "B")

A_plot / B_plot
```

::: {.content-visible when-meta="includeOutlierInterpretation"}
```{r}
#| output: asis
if (check_figure_interpretation) {
  interpretation_text <- interpret_distribution(
    benchmark_data$gestational_age_figure,
    "gestational_age",
    sR
  )

  if (nchar(interpretation_text) > 0) {
    cat("::: {.callout-note}\n")
    cat("##", sR$figure_interpretation$heading, "\n\n")
    cat(interpretation_text, "\n")
    cat(":::\n")
  }
}
```
:::
