To ensure that all partners can base their decisions on valid data, we strive for the highest possible data quality for the individual analyses and reference reports of the NeoIPC surveillance.
Wherever possible, we try to check the validity of the data as soon as it is entered and, if necessary, ask the person entering the data to make corrections.
Unfortunately, our surveillance platform cannot recognize all possible problems at the time of entry.
At regular intervals, especially before reference reports are created, we therefore try to identify these problems using special database queries, summarize them in this report and send it to our partners with a request for correction.
To make the correction as efficient as possible, the report in @sec-problems contains a link for each patient record in which a problem has been identified, which leads directly to the Tracked Entity Instance Dashboard of the patient record in question.
In addition, @sec-problem-details details the issues encountered so that you can understand the potential impact and ways to avoid the problem in the future.
In @sec-solutions we have also outlined the various steps that can be taken to resolve the issue.

::: {.callout-warning}
## Auf Links in per E-Mail erhaltenen Dokumenten klicken

Obwohl wir versuchen, die Behebung von Problemen in Patientenakten so einfach wie möglich zu gestalten, indem wir direkte Links zum Tracked Entity Instance Dashboard bereitstellen, ist dies mit einem gewissen Risiko verbunden.

Wenn Sie zum ersten Mal auf einen solchen Link klicken, werden Sie aufgefordert, Ihre Zugangsdaten (Benutzername und Passwort) für die NeoIPC-Surveillance-Plattform einzugeben.
Verlassen Sie sich bitte nie auf den angezeigten Absender von E-Mails, die Links oder ein Dokument mit Links enthalten und prüfen Sie immer, ob die URL in der Adressleiste Ihres Browsers korrekt ist, bevor Sie Ihre Zugangsdaten eingeben.

Sollte dies nicht der Fall sein, schließen Sie bitte das Browserfenster und informieren Sie uns über unsere [Support-E-Mail-Adresse](mailto:`r support_email_address`).
:::

::: {.content-visible unless-format="html"}
\newpage
:::

## Erkannte Probleme {#sec-problems}

Das folgende ist eine Liste der Patientenakten, bei denen wir irgendeine Art von Problem festgestellt haben. Die Aufzeichnungen sind nach Aufnahmedatum und Ereignisdatum gruppiert.
Wenn eine Patientenakte mehr als ein Problem aufweist, werden alle aufgeführt.
