### Die Patientenakte hat keine Patientenregistrierung {#sec-problem-details-1}

Dieses Problem taucht typischerweise auf, wenn jemand die eingegebenen Daten eines Patienten (eine Patientenakte) löschen wollte, aber stattdessen nur die Patientenregistrierung gelöscht hat.

What remains is a patient record without patient enrolment, which exists in the system as a data orphan.
These patient records will not appear in the list of registered patients and their data cannot be listed in any reports, as most of the information required for analysis is missing.
However, if you try to enter a new patient with the same NeoIPC Patient ID, the system will recognize that this ID is already being used by a different patient and will reject the entry.

Je nachdem, ob sie die in der Patientenakte eingegebenen Daten weiter verwenden möchten oder nicht haben Sie unterschiedliche Möglichkeiten, diese Situation aufzulösen, aber für beide müssen Sie zunächst einmal das Tracked Entity Instance Dashboard der Patientenakte öffnen, was bei Patientenakten ohne Registrierung mit den Standardmitteln von DHIS2 gar nicht so einfach ist.
Wenn Sie noch nicht wissen, wie das funktioniert, lesen Sie bitte @sec-solution-1.

Wenn Sie die das Tracked Entity Instance Dashboard der Patientenakte geöffnet haben, und die Daten nicht erhalten möchten, können Sie die Patientenakte vollständig löschen (siehe @sec-solution-2).
Wenn Sie die Daten erhalten und den betreffenden Patienten in die NeoIPC Surveillance einzuschließen möchten, können Sie stattdessen eine Patientenregistrierung für die Patientenakte anlegen (siehe @sec-solution-3).
