---
lang: en
title: "NeoIPC Reference Report"
params:
  reportingPeriodFrom: NULL
  reportingPeriodTo: NULL
  birthWeightFrom: NULL
  birthWeightTo: NULL
  gestationalAgeFrom: NULL
  gestationalAgeTo: NULL
  countryFilter: NULL
  hospitalFilter: NULL
  testUnitFilter: true
  defaultPatientFilter: true
  token: NULL
---

{{< include _setup.qmd >}}

## Introduction

This is the [NeoIPC Surveillance](https://neoipc.org/surveillance/ "Link to the surveillance section of the NeoIPC website") reference analysis that you can use to assess infection rates in your neonatal unit. If you have your own data collected using the same or a comparable method, you can compare them with the reference values presented in this document and identify any anomalies and potential for improvement.

To enable institutions with limited resources to carry out continuous surveillance and to allow benchmarking against a comparable group of patients, NeoIPC surveillance is limited to high-risk neonates and selected risk factors and infections. Further details can be found in the [NeoIPC Surveillanceprotokoll](https://neoipc.org/wp-content/uploads/2023/08/NeoIPC-Surveillance_Core-Module-Protocol.pdf "Link to the NeoIPC surveillance protocol (pdf, English)").

Taking into account the filtering criteria mentioned above, and thanks to the active cooperation of the departments involved in NeoIPC surveillance, this report includes the complete data sets of a total of *`{r} fn(totPat)` patients* from *`{r} fn(totEnr)` stays* in *`{r} fn(totDept)` departments* with a total of *`{r} fn(totPatDay)` days of surveillance*. The data of a further *`{r} fn(totIncPat)` patients* who were still under active surveillance at the time of the data analysis and who therefore could not yet be analysed, will be available for this analysis as soon as their surveillance has been completed.

## Description of the Population and Its Risk Factors

When we talk about high-risk patients from an infection prevention perspective, we mean that these patients have characteristics that increase their risk of infection. These may be unchangeable patient characteristics or characteristics that can be influenced to a greater or lesser extent by the often complex management of these patients.

When we observe these characteristics epidemiologically, we often call them risk factors, and sometimes also protective factors, which are then seen as the opposite of a risk factor.

In neonates, for example, gestational age, birth weight and postnatal age are prominent patient-specific characteristics that influence the risk of developing an infection (dispositional risk factors).

Examples of characteristics that can be influenced to some degree and that can also influence the risk of infection (known as 'exposure risk factors') include vascular access, mechanical ventilation and breastfeeding, as well as the duration of these interventions (dose effect).

The risk factors observed in the NeoIPC Surveillance and their distribution in the participating partner hospitals are shown below. The expositional risk factors may help to assess the processes in your own department (e.g. indication for therapies), whereas the dispositional risk factors are more suitable for assessing the comparability of your own patient population with the population in the NeoIPC reference database. The more the composition of a unit's patient population differs from that of the NeoIPC Surveillance Reference Report in terms of dispositional risk factors, the less useful the benchmarking will be. Differences and their possible effects must always be carefully considered in interpretation.

### Gestational Age

{{< include figures/_ga-figure.qmd >}}

### Birth Weight

{{< include figures/_bw-figure.qmd >}}

### Further Dispositional Risk Factors

{{< include figures/_sex-figure.qmd >}}

{{< include figures/_multiple-birth-figure.qmd >}}

{{< include figures/_delivery-mode-figure.qmd >}}

### Factors Influencing the Microbiome

#### Antibiotic Use

{{< include tables/_tbl-ab-rates-overall.qmd >}}

{{< include tables/_tbl-ab-rates-aware.qmd >}}
