{{< include _setup.qmd >}}

```{r}
#| include: false
footer_tex <- sprintf("\\renewcommand{\\FooterText}{%s}", sR$h2020_funding_statement)
```

::: {.content-visible when-format="pdf"}
`r footer_tex`
:::

```{r}
#| output: asis
.show(params$includeHeader %||% TRUE)
```

{{< include _header.qmd >}}

::: {.content-visible when-format="pdf"}
\FloatBarrier
:::

```{r}
#| output: asis
.end()
```

## `{r} sR$headings$introduction`

```{r}
#| output: asis
.show(params$includeIntroductionTexts)
```

```{r}
#| output: asis
include_localised("_introduction.Rmd")
```

```{r}
#| output: asis
.end()
```

{{< include content/_introduction-list.qmd >}}

```{r}
#| output: asis
if (params$includeMethodsTexts)
  cat('::: {.content-visible when-meta="alwaysTrue"}\n\n##',
      sR$methods$heading, '\n\n:::\n')
```

```{r}
#| output: asis
.show(params$includeMethodsTexts)
```

```{r}
#| output: asis
include_localised("_methods.Rmd")
```

```{r}
#| output: asis
.end()
```

```{r}
#| output: asis
.show(params$includeTextPatientPopulation)
```

::: {.content-visible when-format="pdf"}
\FloatBarrier
:::

```{r}
#| output: asis
if (params$includeTextPatientPopulation)
  cat('::: {.content-visible when-meta="alwaysTrue"}\n\n##',
      sR$headings$patient_population, '\n\n:::\n')
```

```{r}
#| output: asis
.show(params$includeIntroductionTexts && params$includeTextPatientPopulation)
```

```{r}
#| output: asis
include_localised("_patient_population.Rmd")
```

```{r}
#| output: asis
.end()
```

```{r}
#| output: asis
.show(params$includeMethodsTexts && params$includeTextPatientPopulation)
```

```{r}
#| output: asis
include_localised("_methods-patient-population.Rmd")
```

```{r}
#| output: asis
.end()
```

```{r}
#| output: asis
.end()
```

```{r}
#| output: asis
.show(params$includeBirthWeightFigure)
```

{{< include figures/_fig-bw.qmd >}}

```{r}
#| output: asis
.end()
```

```{r}
#| output: asis
.show(params$includeGestationalAgeFigure)
```

{{< include figures/_fig-ga.qmd >}}

{{< pagebreak >}}

```{r}
#| output: asis
.end()
```

```{r}
#| output: asis
if (show_section_nosocomial)
  cat('::: {.content-visible when-meta="alwaysTrue"}\n\n##',
      sR$headings$nosocomial_infections, '\n\n:::\n')
```

```{r}
#| output: asis
.show(params$includeIntroductionTexts && show_section_nosocomial)
```

```{r}
#| output: asis
include_localised("_nosocomial_infections.Rmd")
```

```{r}
#| output: asis
.end()
```

```{r}
#| output: asis
.show(params$includeIncidenceDensityTable)
```

{{< include tables/_tbl-incidence-density-rates.qmd >}}

{{< pagebreak >}}

```{r}
#| output: asis
.end()
```

```{r}
#| output: asis
.show(params$includeDeviceAssociatedIncidenceDensityTable)
```

{{< include tables/_tbl-device-associated-incidence-density-rates.qmd >}}

{{< pagebreak >}}

```{r}
#| output: asis
.end()
```

```{r}
#| output: asis
.show(params$includeSecondaryBsiRateTable)
```

{{< include tables/_tbl-secondary-bsi-rates.qmd >}}

{{< pagebreak >}}

```{r}
#| output: asis
.end()
```

```{r}
#| output: asis
if (show_section_infectious)
  cat('::: {.content-visible when-meta="alwaysTrue"}\n\n###',
      sR$headings$infectious_agents, '\n\n:::\n')
```

```{r}
#| output: asis
.show(params$includeIntroductionTexts && show_section_infectious)
```

```{r}
#| output: asis
include_localised("_infectious_agents.Rmd")
```

```{r}
#| output: asis
.end()
```

```{r}
#| output: asis
.show(params$includeAgentPerInfectionRateTable)
```

{{< include tables/_tbl-agent-per-infection-rate.qmd >}}

```{r}
#| output: asis
.end()
```

```{r}
#| output: asis
.show(params$includeResistantPathogenInfectionRateTable)
```

{{< include tables/_tbl-abr-infection-rate.qmd >}}

{{< pagebreak >}}

```{r}
#| output: asis
.end()
```

```{r}
#| output: asis
.show(params$includeOrganismResistanceRateTable)
```

{{< include tables/_tbl-organism-resistance-rate.qmd >}}

{{< pagebreak >}}

```{r}
#| output: asis
.end()
```

```{r}
#| output: asis
if (show_section_diagnostics)
  cat('::: {.content-visible when-meta="alwaysTrue"}\n\n###',
      sR$headings$diagnostics, '\n\n:::\n')
```

```{r}
#| output: asis
.show(params$includeInfectiousAgentDetectionRateTable)
```

{{< include tables/_tbl-infectious-agent-detection-rate.qmd >}}

```{r}
#| output: asis
.end()
```

```{r}
#| output: asis
.show(params$includeAntibioticResistanceTestRateTable)
```

{{< include tables/_tbl-resistance-test-rate.qmd >}}

{{< pagebreak >}}

```{r}
#| output: asis
.end()
```

```{r}
#| output: asis
if (show_section_risk)
  cat('::: {.content-visible when-meta="alwaysTrue"}\n\n##',
      sR$headings$risk_and_protective_factors, '\n\n:::\n')
```

```{r}
#| output: asis
.show(params$includeIntroductionTexts && show_section_risk)
```

```{r}
#| output: asis
include_localised("_risk_and_protective_factors.Rmd")
```

```{r}
#| output: asis
.end()
```

```{r}
#| output: asis
.show(params$includeRiskDensityRateTable)
```

{{< include tables/_tbl-risk-density-rates.qmd >}}

{{< pagebreak >}}

```{r}
#| output: asis
.end()
```

```{r}
#| output: asis
.show(params$includeAntibioticUtilisationTable)
```

{{< include tables/_tbl-antibiotic-utilisation.qmd >}}

{{< pagebreak >}}

```{r}
#| output: asis
.end()
```

```{r}
#| output: asis
if (show_section_surgical)
  cat('::: {.content-visible when-meta="alwaysTrue"}\n\n###',
      sR$surgical_procedures, '\n\n:::\n')
```

```{r}
#| output: asis
.show(params$includeIntroductionTexts && show_section_surgical)
```

```{r}
#| output: asis
include_localised("_surgery.Rmd")
```

```{r}
#| output: asis
.end()
```

```{r}
#| output: asis
.show(params$includeSurgicalProcedureRateTable)
```

{{< include tables/_tbl-surgical-procedure-rates.qmd >}}

```{r}
#| output: asis
.end()
```
