title: "Certificate of participation in the NeoIPC project surveillance system (NeoIPC Surveillance)"
format:
  pdf:
    author-meta: "NeoIPC Surveillance team"
    keywords:
      - NeoIPC
      - Surveillance
      - Certificate
