title: "NeoIPC Surveillance Partner Report"
format:
  pdf:
    author-meta: "NeoIPC Surveillance team"
    keywords:
      - NeoIPC
      - Surveillance
      - Partner Report
    include-in-header:
      - file: translations.tex
      - text: |
          \cfoot*{%
            \raggedright
            \hspace{1.6cm}\parbox{0.8\textwidth}{\FooterText}
          }
