project:
  output-dir: _output
date-meta: now
echo: false
# Uncomment for to debug Markdown or LaTeX files
#keep-md: true
#keep-tex: true
number-sections: true
format:
  html:
    link-external-icon: true
    link-external-newwindow: true
  pdf:
    documentclass: scrartcl
    mainfont: "Noto Sans"
    monofont: "Noto Sans"
    fontsize: 10pt
    papersize: a4paper
    fig-pos: 'h'
    colorlinks: true
filters:
  - "../filters/pandoc-quotes.lua"
  - "../filters/fix-unnumbered-bookmarks.lua"
profile:
  group: 
    - [en, de]