## Infectious Agents

Epidemiology of the infectious agents causing nosocomial infections in neonatology is complex and there is a lot of potential for bias. While low diagnostic sensitivity (low blood volume) and specificity (contamination) are a general problem in the neonatal population, the lack of availability of some or all means of microbiological diagnostics, or the lack of financial resources can have a strong effect on the detection rates in resource-constrained settings.

<!-- When comparing data with the information on pathogens presented in @tbl-agent-per-infection-rate and information on drug resistance in @tbl-abr-infection-rate, please also have a look at the infectious agent detection rates presented in @tbl-infectious-agent-detection-rate and the antibiotic resistance test rates in @tbl-resistance-test-rate. -->

In total, `{r} format(reference_data$infectious_agent_detection_rate_per_agent_table |> dplyr::filter(group == "Total") |> dplyr::pull("n"), big.mark = locale_sep_mark)` infectious agents were detected in the `{r} format(reference_data$infectious_agent_detection_rate_per_inf_type_table |> dplyr::filter(inf == "all") |> dplyr::pull("n"), big.mark = locale_sep_mark)` infections that were reported to have yielded at least one agent from either the primary infection and/or the secondary bloodstream infection resulting from it (@tbl-agent-per-infection-rate). These `{r} format(reference_data$infectious_agent_detection_rate_per_inf_type_table |> dplyr::filter(inf == "all") |> dplyr::pull("n"), big.mark = locale_sep_mark)` diagnostic-positive infections out of `{r} format(data |> neoipcr:::get_infection_counts() |> dplyr::pull("n"), big.mark = locale_sep_mark)` overall infections represent an Infectious Agent Detection Rate of `{r} format(((reference_data$infectious_agent_detection_rate_per_inf_type_table |> dplyr::filter(inf == "all") |> dplyr::pull("n")) / (data |> neoipcr:::get_infection_counts() |> dplyr::pull("n")) * 100), digits = 2, nsmall = 1, scientific = FALSE)` per 100 infections (@tbl-infectious-agent-detection-rate).
